# Generated by Django 5.1.7 on 2025-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('quantidade_pacote', models.PositiveIntegerField()),
                ('preco_compra', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('margem_lucro', models.FloatField()),
            ],
        ),
    ]
